host: ""
port: 8317

remote-management:
  allow-remote: true
  secret-key: ""

auth-dir: "/var/data/cli-proxy-api"

api-keys: []

debug: false

commercial-mode: true

logging-to-file: false

usage-statistics-enabled: false

request-retry: 3

max-retry-interval: 30

quota-exceeded:
  switch-project: true
  switch-preview-model: true
  antigravity-credits: true

routing:
  strategy: "round-robin"

ws-auth: false

enable-gemini-cli-endpoint: false

nonstream-keepalive-interval: 0