host: "127.0.0.1"
port: 8317
auth-dir: "~/.cli-proxy-api"
api-keys:
  - "devin-test"
remote-management:
  allow-remote: false
  secret-key: "$2a$10$/5FboDq8MHgoCQxt.RMHxuTCDPaXS7iSpORqjFOsk6XDEiDOC2HV2"
logging-to-file: false
debug: true
