services:
  cli-proxy-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    environment:
      DEPLOY: cloud
      PGSTORE_DSN: "postgresql://lijiahua%40looplaygame.com:LooPlay2026@cpaupdate-cpadb-ziwqd5:5432/postgres?sslmode=disable"
      PGSTORE_SCHEMA: "public"
    ports:
      - "8318:8318"
    volumes:
      - "../files/logs:/CLIProxyAPI/logs"
    restart: unless-stopped
