services:
  cli-proxy-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    environment:
      DEPLOY: cloud
      PGSTORE_DSN: "postgresql://lijiahua%40looplaygame.com:LooPlay2026@cpaupdate-cpadb-ziwqd5:5432/postgres?sslmode=disable"
      PGSTORE_SCHEMA: "public"
    ports:
      - "8318:8318"
    volumes:
      - ${CLI_PROXY_CONFIG_PATH:-./config.yaml}:/CLIProxyAPI/config.yaml
      - ${CLI_PROXY_AUTH_PATH:-./auths}:/root/.cli-proxy-api
      - "../files/logs:/CLIProxyAPI/logs"
      - ${CLI_PROXY_PLUGIN_PATH:-./plugins}:/CLIProxyAPI/plugins
    restart: unless-stopped
