#!/usr/bin/env python3
"""Validate a curated release note before it becomes a GitHub Release body."""

import argparse
import datetime as dt
import re
import sys
from pathlib import Path


VERSION_CORE = r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"
UPSTREAM_VERSION = rf"v{VERSION_CORE}"
# Our releases are vX.Y.Z. The optional suffix records the upstream release the
# tag is aligned to, or "none" for a fork-only release. The suffix is validated
# against the curated note so the tag cannot drift from the recorded alignment.
# The suffix repeats the version without a leading "v": v1.0.2-upstream8.0.5.
UPSTREAM_SUFFIX = rf"-upstream(?:{VERSION_CORE}|none)"
STABLE_TAG = re.compile(rf"{UPSTREAM_VERSION}(?:{UPSTREAM_SUFFIX})?")
TAGGED_UPSTREAM = re.compile(rf"{UPSTREAM_VERSION}-upstream({VERSION_CORE}|none)")
HEADING = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)
LIST_ITEM = re.compile(r"^-\s+\S", re.MULTILINE)
PLACEHOLDER = re.compile(
    r"<(?:describe|summary|version|date|tag|todo)[^>]*>|\b(?:TODO|TBD)\b",
    re.IGNORECASE,
)
ALIGNMENT_FIELDS = (
    "Upstream release",
    "Previous baseline",
    "Intake record",
    "Ported",
    "Skipped",
)
REQUIRED_SECTIONS = (
    "Summary",
    "Upstream alignment",
    "Breaking changes",
    "Added",
    "Changed",
    "Fixed",
    "Security",
    "Validation",
    "Known issues",
)
RELEASE_ASSETS = """<!-- cliproxyapi-linux-release-assets:start -->
## Release assets

- `CLIProxyAPI_<version>_linux_<arch>.tar.gz` is the default Linux build. It supports dynamic library plugins and targets a GLIBC 2.17 baseline.
- `CLIProxyAPI_<version>_linux_<arch>_no-plugin.tar.gz` is the portable Linux build for musl-based or older systems such as OpenWrt. It does not support dynamic library plugins.
- `CLIProxyAPI_<version>_freebsd_aarch64_no-plugin.tar.gz` is the FreeBSD arm64 build. It is built without CGO and does not support dynamic library plugins.

<!-- cliproxyapi-linux-release-assets:end -->"""


def stable_tag(value: str) -> bool:
    return bool(STABLE_TAG.fullmatch(value))


def tag_upstream_claim(tag: str) -> str | None:
    """Return the upstream version a tag claims, "none", or None if absent."""
    match = TAGGED_UPSTREAM.fullmatch(tag)
    return match.group(1) if match else None


def validate_note(tag: str, text: str) -> list[str]:
    errors: list[str] = []
    if not stable_tag(tag):
        errors.append(
            "release tag must be vX.Y.Z with an optional -upstreamX.Y.Z or "
            f"-upstreamnone suffix: {tag}"
        )

    if not text.strip():
        return errors + ["release note is empty"]

    expected_heading = f"# {tag} - "
    first_line = text.splitlines()[0].strip()
    if not first_line.startswith(expected_heading):
        errors.append(f"first heading must start with '{expected_heading}'")
    else:
        date_value = first_line[len(expected_heading):].strip()
        try:
            dt.date.fromisoformat(date_value)
        except ValueError:
            errors.append("release date must use YYYY-MM-DD")

    for match in PLACEHOLDER.finditer(text):
        errors.append(f"placeholder is not allowed: {match.group(0)}")

    headings = [(match.start(), match.end(), match.group(1)) for match in HEADING.finditer(text)]
    section_names = [heading for _, _, heading in headings]
    for name in REQUIRED_SECTIONS:
        count = section_names.count(name)
        if count == 0:
            errors.append(f"missing required section: {name}")
        elif count > 1:
            errors.append(f"duplicate section: {name}")

    sections: dict[str, str] = {}
    for index, (_, start, name) in enumerate(headings):
        end = headings[index + 1][0] if index + 1 < len(headings) else len(text)
        sections.setdefault(name, text[start:end])

    for name in REQUIRED_SECTIONS:
        section = sections.get(name)
        if section and not LIST_ITEM.search(section):
            errors.append(f"section must contain at least one bullet: {name}")

    for name in ("Release assets", "Full changelog"):
        if name in sections:
            errors.append(f"section is generated by the workflow and must be omitted: {name}")

    alignment = sections.get("Upstream alignment", "")
    values = {}
    for field in ALIGNMENT_FIELDS:
        matches = re.findall(
            rf"^- {re.escape(field)}:\s*(\S.*)$",
            alignment,
            re.MULTILINE,
        )
        if len(matches) > 1:
            errors.append(f"duplicate upstream alignment field: {field}")
        values[field] = matches[0].strip() if matches else None
    for field, value in values.items():
        if not value:
            errors.append(f"missing upstream alignment field: {field}")

    upstream_release = values["Upstream release"] or ""
    tagged_upstream = re.fullmatch(rf"`({UPSTREAM_VERSION})`", upstream_release)
    if not tagged_upstream and upstream_release != "none (fork-only release)":
        errors.append(
            "upstream release must be a stable vX.Y.Z tag or "
            "'none (fork-only release)'"
        )

    baseline = values["Previous baseline"] or ""
    tagged_baseline = re.fullmatch(rf"`({UPSTREAM_VERSION})`", baseline)
    if not tagged_baseline and baseline != "none":
        errors.append("previous baseline must be a stable vX.Y.Z tag or 'none'")

    intake_record = values["Intake record"] or ""
    if "ops/upstream-intake/absorbed.md" not in intake_record:
        errors.append("intake record must link to ops/upstream-intake/absorbed.md")

    claim = tag_upstream_claim(tag)
    if claim is not None:
        recorded = "none"
        if tagged_upstream:
            recorded = tagged_upstream.group(1).removeprefix("v")
        if claim != recorded:
            errors.append(
                f"tag claims upstream {claim} but the note records {recorded}; "
                "the tag suffix and the upstream alignment must agree"
            )

    return errors


def render_note(
    tag: str,
    text: str,
    previous_tag: str | None,
    repository: str,
) -> str:
    errors = validate_note(tag, text)
    if errors:
        raise ValueError("\n".join(errors))
    if previous_tag and not stable_tag(previous_tag):
        raise ValueError(f"previous tag must be stable vX.Y.Z: {previous_tag}")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError(f"repository must be owner/name: {repository}")

    if previous_tag:
        changelog = (
            f"[Compare `{previous_tag}`...`{tag}`]"
            f"(https://github.com/{repository}/compare/{previous_tag}...{tag})"
        )
    else:
        changelog = (
            f"[Browse commits up to `{tag}`]"
            f"(https://github.com/{repository}/commits/{tag})"
        )

    return (
        f"{text.rstrip()}\n\n"
        f"{RELEASE_ASSETS}\n\n"
        f"## Full changelog\n\n"
        f"{changelog}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument("tag")
    validate_parser.add_argument("note", type=Path)
    render_parser = subparsers.add_parser("render")
    render_parser.add_argument("tag")
    render_parser.add_argument("note", type=Path)
    render_parser.add_argument("--repository", required=True)
    render_parser.add_argument("--previous-tag")
    render_parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        text = args.note.read_text()
    except OSError as error:
        parser.exit(1, f"error: {error}\n")
    if args.command == "validate":
        errors = validate_note(args.tag, text)
        if errors:
            for error in errors:
                print(f"- {error}", file=sys.stderr)
            parser.exit(1, f"error: {args.note} is not a valid release note\n")
        print(f"Release note is valid: {args.note}")
        return

    try:
        rendered = render_note(
            args.tag, text, args.previous_tag, args.repository,
        )
    except ValueError as error:
        parser.exit(1, f"error: {error}\n")
    if args.output:
        try:
            args.output.write_text(rendered)
        except OSError as error:
            parser.exit(1, f"error: {error}\n")
    else:
        sys.stdout.write(rendered)


if __name__ == "__main__":
    main()
