// Code generated by github.com/router-for-me/CLIProxyAPI/v6/cmd/codegen; DO NOT EDIT.
package synthesizer

import (
	"github.com/router-for-me/CLIProxyAPI/v6/internal/config"
)

// getDedicatedProviderEntries returns the config entries for a dedicated provider.
func (s *ConfigSynthesizer) getDedicatedProviderEntries(p config.ProviderSpec, cfg *config.Config) []config.OAICompatProviderConfig {
	switch p.YAMLKey {
	case "minimax":
		return cfg.MiniMaxKey
	case "roo":
		return cfg.RooKey
	case "kilo":
		return cfg.KiloKey
	case "deepseek":
		return cfg.DeepSeekKey
	case "groq":
		return cfg.GroqKey
	case "mistral":
		return cfg.MistralKey
	case "siliconflow":
		return cfg.SiliconFlowKey
	case "openrouter":
		return cfg.OpenRouterKey
	case "together":
		return cfg.TogetherKey
	case "fireworks":
		return cfg.FireworksKey
	case "novita":
		return cfg.NovitaKey
	}
	return nil
}
