// Code generated from models.dev (opencode-go provider, fetched 2026-09-22T12:57:56Z).
// DO NOT EDIT BY HAND — regenerate with: go run ./cmd/fetch_modelsdev_models
// models.json sections so gateway credentials stay routable when the remote
// catalog carries no matching section (same pattern as the Codex/XAI builtins).
package registry

import "strings"

// Note on the responses set: routing on the Responses protocol is model-driven
// — only these lanes accept /v1/responses natively. Live-probed 2026-09-26:
// the Zen gateway rejects /responses for chat-route models with
// ModelProtocolUnsupported (e.g. mimo-v2.6-flash), so Responses input on those
// translates to /chat/completions. Earlier probing (2026-09-13) had verified
// the mirror case — /chat/completions serves the Responses-native lanes after
// auth — but not this one. The map stays as forward-looking data and documents
// each lane's native protocol.

// modelsdev:routes:begin
// Generated from models.dev per-model provider.npm (the field opencode's
// own client routes on) plus gateway-verified pins. Regen with:
// go run ./cmd/fetch_modelsdev_models
var opencodeAnthropicRouteModels = map[string]bool{
	"minimax-m2.5":  true,
	"minimax-m2.7":  true,
	"minimax-m3":    true,
	"qwen3.8-flash": true,
}

var opencodeResponsesRouteModels = map[string]bool{
	"deepseek-v4-flash":          true,
	"gpt-5.6-luna":               true,
	"gpt-6-luna":                 true,
	"grok-4.5":                   true,
	"grok-4.6":                   true,
	"grok-4.7":                   true,
	"muse-spark-1.2-contributor": true,
	"muse-spark-1.3-contributor": true,
}

// modelsdev:routes:end

// OpencodeUpstreamRoute reports the gateway wire protocol for a model:
// "anthropic" for the Claude-protocol lanes, "responses" for Responses-native
// lanes, "chat" for everything else.
func OpencodeUpstreamRoute(model string) string {
	key := strings.ToLower(strings.TrimSpace(model))
	if openParen := strings.LastIndex(key, "("); openParen >= 0 && strings.HasSuffix(key, ")") {
		key = strings.TrimSpace(key[:openParen])
	}
	if opencodeAnthropicRouteModels[key] {
		return "anthropic"
	}
	if opencodeResponsesRouteModels[key] {
		return "responses"
	}
	return "chat"
}

// OpencodeBuiltinModelInfos placeholder
func opencodeBuiltinModelInfos() []*ModelInfo {
	// modelsdev:generated:begin
	models := make([]*ModelInfo, 0, 42)
	models = append(models, &ModelInfo{
		ID:                        "deepseek-v4-flash",
		Object:                    "model",
		Created:                   1785456000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "DeepSeek V4 Flash",
		Description:               "DeepSeek V4 Flash via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       384000,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          384000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high", "max"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "deepseek-v4-flash-vision-exp",
		Object:                    "model",
		Created:                   1787270400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "DeepSeek V4 Flash Vision Exp",
		Description:               "DeepSeek V4 Flash Vision Exp via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       384000,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          384000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high", "max"}},
		SupportedInputModalities:  []string{"text", "image"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "deepseek-v4-pro",
		Object:                    "model",
		Created:                   1776988800,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "DeepSeek V4 Pro (New)",
		Description:               "DeepSeek V4 Pro (New) via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       384000,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          384000,
		Thinking:                  &ThinkingSupport{Levels: []string{"high", "max"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "deepseek-v4.1-flash",
		Object:                    "model",
		Created:                   1788998400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "DeepSeek V4.1 Flash",
		Description:               "DeepSeek V4.1 Flash via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       384000,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          384000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high", "max"}},
		SupportedInputModalities:  []string{"text", "image"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "glm-5",
		Object:                    "model",
		Created:                   1770768000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GLM-5",
		Description:               "GLM-5 via OpenCode Zen Go.",
		ContextLength:             202752,
		MaxCompletionTokens:       32768,
		InputTokenLimit:           202752,
		OutputTokenLimit:          32768,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "glm-5.1",
		Object:                    "model",
		Created:                   1775520000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GLM-5.1",
		Description:               "GLM-5.1 via OpenCode Zen Go.",
		ContextLength:             202752,
		MaxCompletionTokens:       32768,
		InputTokenLimit:           202752,
		OutputTokenLimit:          32768,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "glm-5.2",
		Object:                    "model",
		Created:                   1781308800,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GLM-5.2",
		Description:               "GLM-5.2 via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"high", "max"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "glm-5.3",
		Object:                    "model",
		Created:                   1786665600,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GLM-5.3",
		Description:               "GLM-5.3 via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high", "max"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "glm-5.3-flash",
		Object:                    "model",
		Created:                   1787702400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GLM-5.3-Flash",
		Description:               "GLM-5.3-Flash via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high", "max"}},
		SupportedInputModalities:  []string{"text", "image", "video", "pdf"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "gpt-5.6-luna",
		Object:                    "model",
		Created:                   1783555200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GPT-5.6 Luna",
		Description:               "GPT-5.6 Luna via OpenCode Zen Go.",
		ContextLength:             1050000,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           922000,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"none", "low", "medium", "high", "xhigh", "max"}},
		SupportedInputModalities:  []string{"text", "image", "pdf"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "gpt-6-luna",
		Object:                    "model",
		Created:                   1790035200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "GPT-6 Luna",
		Description:               "GPT-6 Luna via OpenCode Zen Go.",
		ContextLength:             1050000,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           922000,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"none", "low", "medium", "high", "xhigh", "max"}},
		SupportedInputModalities:  []string{"text", "image", "pdf"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "grok-4.5",
		Object:                    "model",
		Created:                   1783468800,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Grok 4.5",
		Description:               "Grok 4.5 via OpenCode Zen Go.",
		ContextLength:             500000,
		MaxCompletionTokens:       500000,
		InputTokenLimit:           500000,
		OutputTokenLimit:          500000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "grok-4.6",
		Object:                    "model",
		Created:                   1786492800,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Grok 4.6",
		Description:               "Grok 4.6 via OpenCode Zen Go.",
		ContextLength:             500000,
		MaxCompletionTokens:       500000,
		InputTokenLimit:           500000,
		OutputTokenLimit:          500000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}},
		SupportedInputModalities:  []string{"text", "image"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "grok-4.7",
		Object:                    "model",
		Created:                   1789948800,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Grok 4.7",
		Description:               "Grok 4.7 via OpenCode Zen Go.",
		ContextLength:             500000,
		MaxCompletionTokens:       500000,
		InputTokenLimit:           500000,
		OutputTokenLimit:          500000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}},
		SupportedInputModalities:  []string{"text", "image", "pdf"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "hy3",
		Object:                    "model",
		Created:                   1783296000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Hy3",
		Description:               "Hy3 via OpenCode Zen Go.",
		ContextLength:             256000,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           192000,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"none", "low", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "hy4-preview",
		Object:                    "model",
		Created:                   1787875200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Hy4 preview",
		Description:               "Hy4 preview via OpenCode Zen Go.",
		ContextLength:             1024000,
		MaxCompletionTokens:       64000,
		InputTokenLimit:           1024000,
		OutputTokenLimit:          64000,
		Thinking:                  &ThinkingSupport{Levels: []string{"none", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "kimi-k2.5",
		Object:                    "model",
		Created:                   1769472000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Kimi K2.5",
		Description:               "Kimi K2.5 via OpenCode Zen Go.",
		ContextLength:             262144,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           262144,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "kimi-k2.6",
		Object:                    "model",
		Created:                   1776729600,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Kimi K2.6",
		Description:               "Kimi K2.6 via OpenCode Zen Go.",
		ContextLength:             262144,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           262144,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "kimi-k2.7-code",
		Object:                    "model",
		Created:                   1781222400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Kimi K2.7 Code",
		Description:               "Kimi K2.7 Code via OpenCode Zen Go.",
		ContextLength:             262144,
		MaxCompletionTokens:       262144,
		InputTokenLimit:           262144,
		OutputTokenLimit:          262144,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "kimi-k3",
		Object:                    "model",
		Created:                   1784160000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Kimi K3",
		Description:               "Kimi K3 via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"max"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "longcat-2.0",
		Object:                    "model",
		Created:                   1782777600,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "LongCat-2.0",
		Description:               "LongCat-2.0 via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "longcat-2.5-preview-free",
		Object:                    "model",
		Created:                   1790294400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "LongCat 2.5 Preview Free",
		Description:               "LongCat 2.5 Preview Free via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "mimo-v2-omni",
		Object:                    "model",
		Created:                   1773792000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiMo V2 Omni",
		Description:               "MiMo V2 Omni via OpenCode Zen Go.",
		ContextLength:             262144,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           262144,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "audio", "pdf"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "mimo-v2-pro",
		Object:                    "model",
		Created:                   1773792000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiMo V2 Pro",
		Description:               "MiMo V2 Pro via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "mimo-v2.5",
		Object:                    "model",
		Created:                   1776816000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiMo V2.5",
		Description:               "MiMo V2.5 via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "audio", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "mimo-v2.5-pro",
		Object:                    "model",
		Created:                   1776816000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiMo V2.5 Pro",
		Description:               "MiMo V2.5 Pro via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "mimo-v2.6-flash",
		Object:                    "model",
		Created:                   1790035200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiMo-V2.6-Flash",
		Description:               "MiMo-V2.6-Flash via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "audio", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "mimo-v2.6-pro",
		Object:                    "model",
		Created:                   1790035200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiMo-V2.6-Pro",
		Description:               "MiMo-V2.6-Pro via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "audio", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "minimax-m2.5",
		Object:                    "model",
		Created:                   1770854400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiniMax-M2.5",
		Description:               "MiniMax-M2.5 via OpenCode Zen Go.",
		ContextLength:             204800,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           204800,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "minimax-m2.7",
		Object:                    "model",
		Created:                   1773792000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiniMax-M2.7",
		Description:               "MiniMax-M2.7 via OpenCode Zen Go.",
		ContextLength:             204800,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           204800,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "minimax-m3",
		Object:                    "model",
		Created:                   1780185600,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "MiniMax-M3",
		Description:               "MiniMax-M3 via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "muse-spark-1.2-contributor",
		Object:                    "model",
		Created:                   1785888000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Muse Spark 1.2 Contributor",
		Description:               "Muse Spark 1.2 Contributor via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh"}},
		SupportedInputModalities:  []string{"text", "image", "video", "pdf", "audio"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "muse-spark-1.3-contributor",
		Object:                    "model",
		Created:                   1788307200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Muse Spark 1.3 Contributor",
		Description:               "Muse Spark 1.3 Contributor via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1048576,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh"}},
		SupportedInputModalities:  []string{"text", "image", "video", "pdf", "audio"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "omen-alpha",
		Object:                    "model",
		Created:                   1788480000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Omen Alpha",
		Description:               "Omen Alpha via OpenCode Zen Go.",
		ContextLength:             500000,
		MaxCompletionTokens:       128000,
		InputTokenLimit:           500000,
		OutputTokenLimit:          128000,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high"}},
		SupportedInputModalities:  []string{"text", "image"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "ox-alpha-free",
		Object:                    "model",
		Created:                   1787270400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Ox Alpha Free (Unlimited)",
		Description:               "Ox Alpha Free (Unlimited) via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "high", "max"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "qwen3.5-plus",
		Object:                    "model",
		Created:                   1771200000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Qwen3.5 Plus",
		Description:               "Qwen3.5 Plus via OpenCode Zen Go.",
		ContextLength:             262144,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           262144,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "qwen3.6-plus",
		Object:                    "model",
		Created:                   1775088000,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Qwen3.6 Plus",
		Description:               "Qwen3.6 Plus via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "qwen3.7-max",
		Object:                    "model",
		Created:                   1779321600,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Qwen3.7 Max",
		Description:               "Qwen3.7 Max via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "qwen3.7-plus",
		Object:                    "model",
		Created:                   1780358400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Qwen3.7 Plus",
		Description:               "Qwen3.7 Plus via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       65536,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          65536,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "qwen3.8-flash",
		Object:                    "model",
		Created:                   1787702400,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Qwen3.8 Flash",
		Description:               "Qwen3.8 Flash via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "xhigh"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "qwen3.8-max",
		Object:                    "model",
		Created:                   1785715200,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Qwen3.8 Max",
		Description:               "Qwen3.8 Max via OpenCode Zen Go.",
		ContextLength:             1000000,
		MaxCompletionTokens:       131072,
		InputTokenLimit:           1000000,
		OutputTokenLimit:          131072,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "xhigh"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice", "response_format", "temperature"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	models = append(models, &ModelInfo{
		ID:                        "space-bunny-free",
		Object:                    "model",
		Created:                   1790121600,
		OwnedBy:                   "opencode",
		Type:                      "opencode",
		DisplayName:               "Space Bunny Free",
		Description:               "Space Bunny Free via OpenCode Zen Go.",
		ContextLength:             1048576,
		MaxCompletionTokens:       524288,
		InputTokenLimit:           524288,
		OutputTokenLimit:          524288,
		Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh", "max"}},
		SupportedInputModalities:  []string{"text", "image", "video"},
		SupportedOutputModalities: []string{"text"},
		SupportedParameters:       []string{"tool_choice"},
		ExplicitThinking:          true,
		ExplicitInputModalities:   true,
	})
	// modelsdev:generated:end
	return models
}

// WithOpencodeBuiltins upserts the hard-coded Zen Go lane snapshot over catalog entries.
func WithOpencodeBuiltins(models []*ModelInfo) []*ModelInfo {
	return upsertModelInfos(models, opencodeBuiltinModelInfos()...)
}
