// Code generated by github.com/router-for-me/CLIProxyAPI/v6/cmd/codegen; DO NOT EDIT.
package diff

import (
	"fmt"
	"github.com/router-for-me/CLIProxyAPI/v6/pkg/llmproxy/config"
)

// BuildConfigChangeDetailsGeneratedProviders computes changes for generated dedicated providers.
func BuildConfigChangeDetailsGeneratedProviders(oldCfg, newCfg *config.Config, changes *[]string) {
	if len(oldCfg.MiniMaxKey) != len(newCfg.MiniMaxKey) {
		*changes = append(*changes, fmt.Sprintf("minimax: count %d -> %d", len(oldCfg.MiniMaxKey), len(newCfg.MiniMaxKey)))
	}
	if len(oldCfg.RooKey) != len(newCfg.RooKey) {
		*changes = append(*changes, fmt.Sprintf("roo: count %d -> %d", len(oldCfg.RooKey), len(newCfg.RooKey)))
	}
	if len(oldCfg.KiloKey) != len(newCfg.KiloKey) {
		*changes = append(*changes, fmt.Sprintf("kilo: count %d -> %d", len(oldCfg.KiloKey), len(newCfg.KiloKey)))
	}
	if len(oldCfg.DeepSeekKey) != len(newCfg.DeepSeekKey) {
		*changes = append(*changes, fmt.Sprintf("deepseek: count %d -> %d", len(oldCfg.DeepSeekKey), len(newCfg.DeepSeekKey)))
	}
	if len(oldCfg.GroqKey) != len(newCfg.GroqKey) {
		*changes = append(*changes, fmt.Sprintf("groq: count %d -> %d", len(oldCfg.GroqKey), len(newCfg.GroqKey)))
	}
	if len(oldCfg.MistralKey) != len(newCfg.MistralKey) {
		*changes = append(*changes, fmt.Sprintf("mistral: count %d -> %d", len(oldCfg.MistralKey), len(newCfg.MistralKey)))
	}
	if len(oldCfg.SiliconFlowKey) != len(newCfg.SiliconFlowKey) {
		*changes = append(*changes, fmt.Sprintf("siliconflow: count %d -> %d", len(oldCfg.SiliconFlowKey), len(newCfg.SiliconFlowKey)))
	}
	if len(oldCfg.OpenRouterKey) != len(newCfg.OpenRouterKey) {
		*changes = append(*changes, fmt.Sprintf("openrouter: count %d -> %d", len(oldCfg.OpenRouterKey), len(newCfg.OpenRouterKey)))
	}
	if len(oldCfg.TogetherKey) != len(newCfg.TogetherKey) {
		*changes = append(*changes, fmt.Sprintf("together: count %d -> %d", len(oldCfg.TogetherKey), len(newCfg.TogetherKey)))
	}
	if len(oldCfg.FireworksKey) != len(newCfg.FireworksKey) {
		*changes = append(*changes, fmt.Sprintf("fireworks: count %d -> %d", len(oldCfg.FireworksKey), len(newCfg.FireworksKey)))
	}
	if len(oldCfg.NovitaKey) != len(newCfg.NovitaKey) {
		*changes = append(*changes, fmt.Sprintf("novita: count %d -> %d", len(oldCfg.NovitaKey), len(newCfg.NovitaKey)))
	}
}
