package store

import (
	"fmt"
	"testing"
	"time"
)

// TestSelectErrorCountWithErrorClassFilter guards Task 9b: the error_class and
// error_fingerprint WHERE clauses generated by buildWhereClause must correctly
// narrow the usage_errors rows. These are errors-only columns; events-path
// callers never set them (they default to "" in the filter struct and
// buildWhereClause's AND arms do not fire).
func TestSelectErrorCountWithErrorClassFilter(t *testing.T) {
	store := newTestPostgresStore(t, "err_class_filter")
	ctx := cancelableTestCtx(t)
	us := NewUsageStore(store)

	apiKeys := NewAPIKeyStore(store)
	key, _, err := apiKeys.Create(ctx, "ecf", "", "", nil, nil, nil)
	if err != nil {
		t.Fatalf("Create api key: %v", err)
	}

	now := time.Now().UTC()

	// Insert: 2 rate_limit rows (same class) and 1 auth row.
	for i := 0; i < 2; i++ {
		if err := us.InsertError(ctx, UsageError{
			APIKeyID:         key.ID,
			Provider:         "test-prov",
			Model:            "test-model",
			FailStatusCode:   429,
			ErrorMessage:     fmt.Sprintf("rate limit %d", i),
			ErrorClass:       "rate_limit",
			ErrorFingerprint: fmt.Sprintf("ratefp%02d", i),
			RequestedAt:      now.Add(-time.Duration(i) * time.Second),
		}); err != nil {
			t.Fatalf("InsertError rate_limit %d: %v", i, err)
		}
	}
	if err := us.InsertError(ctx, UsageError{
		APIKeyID:         key.ID,
		Provider:         "test-prov",
		Model:            "test-model",
		FailStatusCode:   401,
		ErrorMessage:     "auth fail",
		ErrorClass:       "auth",
		ErrorFingerprint: "authfp",
		RequestedAt:      now,
	}); err != nil {
		t.Fatalf("InsertError auth: %v", err)
	}

	// Filter by error_class = "rate_limit": should return 2.
	count, err := us.SelectErrorCount(ctx, UsageFilter{
		APIKeyID:   key.ID,
		ErrorClass: "rate_limit",
		From:       now.Add(-time.Hour),
	})
	if err != nil {
		t.Fatalf("SelectErrorCount(error_class=rate_limit): %v", err)
	}
	if count != 2 {
		t.Errorf("count(error_class=rate_limit) = %d; want 2", count)
	}

	// Filter by error_class = "auth": should return 1.
	countAuth, err := us.SelectErrorCount(ctx, UsageFilter{
		APIKeyID:   key.ID,
		ErrorClass: "auth",
		From:       now.Add(-time.Hour),
	})
	if err != nil {
		t.Fatalf("SelectErrorCount(error_class=auth): %v", err)
	}
	if countAuth != 1 {
		t.Errorf("count(error_class=auth) = %d; want 1", countAuth)
	}

	// Filter by ErrorFingerprint: should match exactly 1 row.
	countFp, err := us.SelectErrorCount(ctx, UsageFilter{
		APIKeyID:         key.ID,
		ErrorFingerprint: "ratefp00",
		From:             now.Add(-time.Hour),
	})
	if err != nil {
		t.Fatalf("SelectErrorCount(error_fingerprint=ratefp00): %v", err)
	}
	if countFp != 1 {
		t.Errorf("count(error_fingerprint=ratefp00) = %d; want 1", countFp)
	}

	// Combine ErrorClass with an existing filter field (Provider): both arms bind.
	countCombined, err := us.SelectErrorCount(ctx, UsageFilter{
		APIKeyID:   key.ID,
		Provider:   "test-prov",
		ErrorClass: "rate_limit",
		From:       now.Add(-time.Hour),
	})
	if err != nil {
		t.Fatalf("SelectErrorCount(provider=test-prov, error_class=rate_limit): %v", err)
	}
	if countCombined != 2 {
		t.Errorf("count(provider=test-prov, error_class=rate_limit) = %d; want 2", countCombined)
	}
}
