// Code generated by github.com/router-for-me/CLIProxyAPI/v6/cmd/codegen; DO NOT EDIT.
package config

import "strings"

// GeneratedConfig contains generated config fields for dedicated providers.
type GeneratedConfig struct {
	// MiniMaxKey defines MiniMax configurations.
	MiniMaxKey []MiniMaxKey `yaml:"minimax" json:"minimax"`
	// RooKey defines Roo configurations.
	RooKey []RooKey `yaml:"roo" json:"roo"`
	// KiloKey defines Kilo configurations.
	KiloKey []KiloKey `yaml:"kilo" json:"kilo"`
	// DeepSeekKey defines DeepSeek configurations.
	DeepSeekKey []DeepSeekKey `yaml:"deepseek" json:"deepseek"`
	// GroqKey defines Groq configurations.
	GroqKey []GroqKey `yaml:"groq" json:"groq"`
	// MistralKey defines Mistral configurations.
	MistralKey []MistralKey `yaml:"mistral" json:"mistral"`
	// SiliconFlowKey defines SiliconFlow configurations.
	SiliconFlowKey []SiliconFlowKey `yaml:"siliconflow" json:"siliconflow"`
	// OpenRouterKey defines OpenRouter configurations.
	OpenRouterKey []OpenRouterKey `yaml:"openrouter" json:"openrouter"`
	// TogetherKey defines Together configurations.
	TogetherKey []TogetherKey `yaml:"together" json:"together"`
	// FireworksKey defines Fireworks configurations.
	FireworksKey []FireworksKey `yaml:"fireworks" json:"fireworks"`
	// NovitaKey defines Novita configurations.
	NovitaKey []NovitaKey `yaml:"novita" json:"novita"`
}

// MiniMaxKey is a type alias for OAICompatProviderConfig for the minimax provider.
type MiniMaxKey = OAICompatProviderConfig

// RooKey is a type alias for OAICompatProviderConfig for the roo provider.
type RooKey = OAICompatProviderConfig

// KiloKey is a type alias for OAICompatProviderConfig for the kilo provider.
type KiloKey = OAICompatProviderConfig

// DeepSeekKey is a type alias for OAICompatProviderConfig for the deepseek provider.
type DeepSeekKey = OAICompatProviderConfig

// GroqKey is a type alias for OAICompatProviderConfig for the groq provider.
type GroqKey = OAICompatProviderConfig

// MistralKey is a type alias for OAICompatProviderConfig for the mistral provider.
type MistralKey = OAICompatProviderConfig

// SiliconFlowKey is a type alias for OAICompatProviderConfig for the siliconflow provider.
type SiliconFlowKey = OAICompatProviderConfig

// OpenRouterKey is a type alias for OAICompatProviderConfig for the openrouter provider.
type OpenRouterKey = OAICompatProviderConfig

// TogetherKey is a type alias for OAICompatProviderConfig for the together provider.
type TogetherKey = OAICompatProviderConfig

// FireworksKey is a type alias for OAICompatProviderConfig for the fireworks provider.
type FireworksKey = OAICompatProviderConfig

// NovitaKey is a type alias for OAICompatProviderConfig for the novita provider.
type NovitaKey = OAICompatProviderConfig

// SanitizeGeneratedProviders trims whitespace from generated provider credential fields.
func (cfg *Config) SanitizeGeneratedProviders() {
	if cfg == nil {
		return
	}
	for i := range cfg.MiniMaxKey {
		entry := &cfg.MiniMaxKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.RooKey {
		entry := &cfg.RooKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.KiloKey {
		entry := &cfg.KiloKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.DeepSeekKey {
		entry := &cfg.DeepSeekKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.GroqKey {
		entry := &cfg.GroqKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.MistralKey {
		entry := &cfg.MistralKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.SiliconFlowKey {
		entry := &cfg.SiliconFlowKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.OpenRouterKey {
		entry := &cfg.OpenRouterKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.TogetherKey {
		entry := &cfg.TogetherKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.FireworksKey {
		entry := &cfg.FireworksKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
	for i := range cfg.NovitaKey {
		entry := &cfg.NovitaKey[i]
		entry.TokenFile = strings.TrimSpace(entry.TokenFile)
		entry.APIKey = strings.TrimSpace(entry.APIKey)
		entry.BaseURL = strings.TrimSpace(entry.BaseURL)
		entry.ProxyURL = strings.TrimSpace(entry.ProxyURL)
	}
}
