// Code generated by github.com/router-for-me/CLIProxyAPI/v6/cmd/codegen; DO NOT EDIT.
package config

// GeneratedConfig contains generated config fields for dedicated providers.
type GeneratedConfig struct {
	// MinimaxKey defines Minimax configurations.
	MinimaxKey []MinimaxKey `yaml:"minimax" json:"minimax"`
	// RooKey defines Roo configurations.
	RooKey []RooKey `yaml:"roo" json:"roo"`
	// KiloKey defines Kilo configurations.
	KiloKey []KiloKey `yaml:"kilo" json:"kilo"`
	// DeepseekKey defines Deepseek configurations.
	DeepseekKey []DeepseekKey `yaml:"deepseek" json:"deepseek"`
	// GroqKey defines Groq configurations.
	GroqKey []GroqKey `yaml:"groq" json:"groq"`
	// MistralKey defines Mistral configurations.
	MistralKey []MistralKey `yaml:"mistral" json:"mistral"`
	// SiliconflowKey defines Siliconflow configurations.
	SiliconflowKey []SiliconflowKey `yaml:"siliconflow" json:"siliconflow"`
	// OpenrouterKey defines Openrouter configurations.
	OpenrouterKey []OpenrouterKey `yaml:"openrouter" json:"openrouter"`
	// TogetherKey defines Together configurations.
	TogetherKey []TogetherKey `yaml:"together" json:"together"`
	// FireworksKey defines Fireworks configurations.
	FireworksKey []FireworksKey `yaml:"fireworks" json:"fireworks"`
	// NovitaKey defines Novita configurations.
	NovitaKey []NovitaKey `yaml:"novita" json:"novita"`
}

// MinimaxKey is a type alias for OAICompatProviderConfig for the minimax provider.
type MinimaxKey = OAICompatProviderConfig

// RooKey is a type alias for OAICompatProviderConfig for the roo provider.
type RooKey = OAICompatProviderConfig

// KiloKey is a type alias for OAICompatProviderConfig for the kilo provider.
type KiloKey = OAICompatProviderConfig

// DeepseekKey is a type alias for OAICompatProviderConfig for the deepseek provider.
type DeepseekKey = OAICompatProviderConfig

// GroqKey is a type alias for OAICompatProviderConfig for the groq provider.
type GroqKey = OAICompatProviderConfig

// MistralKey is a type alias for OAICompatProviderConfig for the mistral provider.
type MistralKey = OAICompatProviderConfig

// SiliconflowKey is a type alias for OAICompatProviderConfig for the siliconflow provider.
type SiliconflowKey = OAICompatProviderConfig

// OpenrouterKey is a type alias for OAICompatProviderConfig for the openrouter provider.
type OpenrouterKey = OAICompatProviderConfig

// TogetherKey is a type alias for OAICompatProviderConfig for the together provider.
type TogetherKey = OAICompatProviderConfig

// FireworksKey is a type alias for OAICompatProviderConfig for the fireworks provider.
type FireworksKey = OAICompatProviderConfig

// NovitaKey is a type alias for OAICompatProviderConfig for the novita provider.
type NovitaKey = OAICompatProviderConfig
