#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Regenerate into a temp file, compare to committed.
uv run --project .. python ../scripts/dump_openapi.py
pnpm exec openapi-typescript openapi.json -o /tmp/types.fresh.ts
{
  echo "// AUTO-GENERATED by \`make api-types\`. DO NOT EDIT."
  echo "// Source: usage_dashboard.api:app.openapi()"
  echo ""
  cat /tmp/types.fresh.ts
} > /tmp/types.fresh.ts.tmp
mv /tmp/types.fresh.ts.tmp /tmp/types.fresh.ts

if ! diff -q src/api/types.ts /tmp/types.fresh.ts >/dev/null; then
  echo "ERROR: src/api/types.ts is stale. Run 'make api-types' and commit."
  diff src/api/types.ts /tmp/types.fresh.ts | head -50
  exit 1
fi
echo "types.ts is fresh."