#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
uv run --project .. python ../scripts/dump_openapi.py
pnpm exec openapi-typescript openapi.json -o src/api/types.ts
# Prepend auto-generated header
{
  echo "// AUTO-GENERATED by \`make api-types\`. DO NOT EDIT."
  echo "// Source: usage_dashboard.api:app.openapi()"
  echo ""
  cat src/api/types.ts
} > src/api/types.ts.tmp
mv src/api/types.ts.tmp src/api/types.ts